version: "3.7"
services:

  vts-mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mgadmin
      - MONGO_INITDB_ROOT_PASSWORD=Password1
      - MONGO_INITDB_DATABASE=tvt
    ports:
      - "27017:27017"
    networks:
      - vts-network
    volumes:
      - "database-volume:/data/db"
      - "./initializer:/docker-entrypoint-initdb.d"

  vts-dashboard:
    image: ariman/tvt-dashboard:latest
#    image: tvt-dashboard:latest
    environment:
      - TVT_ENV=docker
      - TVT_FS_HOST_URL=http://localhost:8123
      - TVT_DB_USERNAME=tvt-user
      - TVT_DB_PASSWORD=tvt-password
    ports:
      - "3001:3001"
    volumes:
      - "exchange-volume:/exchange"
    networks:
      - vts-network

  vts-slave:
    image: ariman/tvt-slave:latest
#    image: tvt-slave:latest
    environment:
      - TVT_ENV=docker
      - TVT_FS_HOST_URL=http://localhost:8123
      - TVT_DB_USERNAME=tvt-user
      - TVT_DB_PASSWORD=tvt-password
    ports:
      - "3002:3002"
    volumes:
      - "exchange-volume:/exchange"
    networks:
      - vts-network

  vts-exchange:
    image: ariman/tvt-exchange:latest
#    image: tvt-exchange:latest
    environment:
      - TVT_ENV=docker
    ports:
      - "3003:3003"
    volumes:
      - "exchange-volume:/exchange"
    networks:
      - vts-network

  vts-file-service:
    image: ariman/tvt-file-service:latest
#    image: tvt-file-service:latest
    ports:
      - "8123:8123"
    volumes:
      - "exchange-volume:/exchange"
    networks:
      - vts-network

volumes:
  database-volume:
  exchange-volume:

networks:
  vts-network:
