version: "3.7"
services:

  vcer-mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - "./mount-volume/mysql-volume:/var/lib/mysql"
    networks:
      - vcer-keycloak-network

  vcer-keycloak:
    image: jboss/keycloak:5.0.0
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Password1
    networks:
      - vcer-keycloak-network

networks:
  vcer-keycloak-network: