version: "3.7"
services:

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - "./mount-volume/postgresql-volume/keycloak-volume-5:/var/lib/postgresql/data"
    networks:
      - vcer-infra-network

  vcer-keycloak:
    image: jboss/keycloak:5.0.0
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Password1
    networks:
      - vcer-infra-network

networks:
  vcer-infra-network:
    name: vcer-infra-network
    external: true