version: "3.7"
services:

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - "./mount-volume/postgresql-volume/keycloak-volume-8:/var/lib/postgresql/data"
    networks:
      - vcer-keycloak-network-8

  vcer-keycloak:
    image: jboss/keycloak:8.0.1
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Password1
    networks:
      - vcer-keycloak-network-8

networks:
  vcer-keycloak-network-8: