version: "3.7"
services:

  vts-mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - vts-network
    volumes:
      - "./mount-volume/vts-mongodb:/data/db"

  vts-exchange:
    image: vts-exchange:latest
    ports:
      - "8080:8080"
    volumes:
      - "/Users/Biao/Workspace/Webber/exchange:/exchange"
    networks:
      - vts-network

  vts-dashboard:
    image: vts-dashboard:latest
    ports:
      - "3001:3001"
    volumes:
      - "/Users/Biao/Workspace/Webber/exchange:/exchange"
    networks:
      - vts-network

  vts-slave:
    image: vts-slave:latest
    ports:
      - "3002:3002"
    volumes:
      - "/Users/Biao/Workspace/Webber/exchange:/exchange"
    networks:
      - vts-network

networks:
  # this network must be manually created before deploy this compose file.
  # > docker network create -d overlay --attachable vts-network
  vts-network:
    name: vts-network
    external: true
