version: "3.7"
services:

  wm-mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mgadmin
      - MONGO_INITDB_ROOT_PASSWORD=Password1
      - MONGO_INITDB_DATABASE=weasy-mock
    ports:
      - "27017:27017"
    networks:
      - wm-network
    volumes:
      - "./mount-volume/mongo-volume/weasy-mock:/data/db"
      - "./initializer/mongodb/weasy-mock:/docker-entrypoint-initdb.d"

  wm-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - wm-network

  wm-weasymock:
    image: ariman/weasy-mock:latest
    environment:
      - WM_DB_USERNAME=wm-user
      - WM_DB_PASSWORD=wm-password
    ports:
      - "7300:7300"
    networks:
      - wm-network
    depends_on:
      - wm-mongo
      - wm-redis
    restart: on-failure

  wm-wadapter:
    image: ariman/wadapter:latest
    environment:
      - WM_DB_USERNAME=wm-user
      - WM_DB_PASSWORD=wm-password
    ports:
      - "8081:8081"
      - "9100-9600:9100-9600"
    networks:
      - wm-network
    depends_on:
      - wm-mongo
      - wm-redis
    restart: on-failure

networks:
  # this network must be manually created before deploy this compose file.
  # > docker network create -d overlay --attachable wm-network
  wm-network:
    name: wm-network
    external: true
